### ISSUE TITLE
balena build: SecretRemovalError: The command '/bin/sh -c apk update && apk add jq' returned a non-zero code: 1

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1355]
Introduced in v11.7.0 as part of multibuild, somehow [one](https://github.com/balena-io-modules/resin-multibuild/blob/fb3339396a4495888fd060ea5fbcbb08555a007c/lib/build-secrets/Dockerfile.remove) of these [two](https://github.com/balena-io-modules/resin-multibuild/blob/fb3339396a4495888fd060ea5fbcbb08555a007c/lib/build-secrets/Dockerfile) is injected improperly or incompletely into an `armv7hf` Debian build which fails with the following stacktrace:

```
SecretRemovalError: The command '/bin/sh -c apk update && apk add jq' returned a non-zero code: 1
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:122:19)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:5:65)
    at <anonymous>
```

For a simple reproduction:

Dockerfile:
```
FROM balenalib/raspberrypi3-debian:jessie-build
```
cmd:
```
balena build --deviceType raspberrypi3 --arch armv7hf
```

Downgrading to 11.6.1 works around the issue for now (cc @CameronDiver & @pdcastro).

**Comment by pdcastro** [comment]
This issue was fixed in CLI [v11.9.0](https://github.com/balena-io/balena-cli/releases).

**Comment by misk** [comment]
I am using 11.9.1 and the issue is still there

**`> balena push 192.168.1.217 -s .`**
`SecretRemovalError: The command '/bin/sh -c apk update && apk add bash jq' returned a non-zero code: 139
    at Object.<anonymous> (/usr/local/lib/balena-cli/node_modules/resin-multibuild/build/index.js:124:19)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/balena-cli/node_modules/resin-multibuild/build/index.js:5:65)`

**`> balena -v`**
`[debug] original argv0="/usr/local/lib/balena-cli/bin/node" argv=[/usr/local/lib/balena-cli/bin/node,/usr/local/lib/balena-cli/bin/run,-v] length=3
[debug] new argv=[/usr/local/lib/balena-cli/bin/node,/usr/local/lib/balena-cli/bin/run,version] length=3
11.9.1
`

**Comment by pdcastro** [comment]
@misk, sorry to hear that. To help debugging it, what is the device type you were pushing to? (device of IP address 192.168.1.217) -- like Raspberry Pi 3, Intel NUC, ...  And the computer where you were running the CLI, does it run Linux or Mac or Windows?

**Comment by xginn8** [comment]
@pdcastro i noticed this too, Linux pushing to a local mode NUC (BoB). I don't know if it's related, but i noted many failing DNS lookups around the same time.

**Comment by pdcastro** [comment]
Thanks @xginn8. The original error reported in this issue included `"returned a non-zero code: 1"`, and it was related to mismatched processor architecture. Then after CLI release v11.9.0, the error observed by @misk was `"returned a non-zero code: 139"` (1 vs 139). Adding your observation of _"many failing DNS lookups around the same time"_ and this [docker-alpine issue](https://github.com/gliderlabs/docker-alpine/issues/180) I found, my best guess is that the `apk` command is failing for its own apk-ey reasons. The CLI / multibuild code runs this [Dockerfile.remove](https://github.com/balena-io-modules/resin-multibuild/blob/v4.0.2/lib/build-secrets/Dockerfile.remove) file:
```
FROM %%ARCH%%/alpine:3.10
RUN apk update && apk add bash jq
...
```
My current thinking of how to solve this is to prebuild an image including `bash` and `jq` instead of running `apk update && apk add bash jq` every time, which should also make it a bit faster. And one thing is for sure: if the `apk` line is deleted, there won't be `apk` errors reported! Well, not on that Dockerfile line anyway. :-)

**Comment by misk** [comment]
@pdcastro I am using RPi Zero W with balenaOS 2.32.0+rev1. Running on OSX 10.14.6.

I used example https://github.com/balena-io-projects/balena-c-hello-world and tried to deploy it locally.

**Comment by JakeCover** [comment]
This doesn't seem to be fixed as of CLI version 11.14.0. Just updated it because of this error, but it's still occuring, _specifically error 139 not 1_ (Balena directory shortened later for space)
```bash
name@my-computer:folder$ /mnt/c/Users/jdc10/PycharmProjects/RedditReposter/balena-cli/balena  -v
11.14.0

name@my-computer:folder$ balena push 192.168.1.30
[Info]    Starting build on device 192.168.1.30
[Info]    Compose file detected
The command '/bin/sh -c apk update && apk add bash jq' returned a non-zero code: 139

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

With debug on:
```
name@my-computer:folder$ balena push 192.168.1.30
[debug] original argv0="/mnt/c/Users/jdc10/PycharmProjects/RedditReposter/balena-cli/balena" argv=[/mnt/c/Users/jdc10/PycharmProjects/RedditReposter/balena-cli/balena,/snapshot/versioned-source/bin/balena,push,192.168.1.30] length=4
[debug] Using . as build source
[Debug]   Checking we can access device
[Debug]   Sending request to http://192.168.1.30:48484/ping
[Debug]   Checking device version: 9.14.0
[Info]    Starting build on device 192.168.1.30
[Debug]   Loading project...
[Debug]   Resolving project...
[Info]    Compose file detected
[Debug]   Creating project...
[Debug]   Tarring all non-ignored files...
[Debug]   Sending request to http://192.168.1.30:48484/v2/local/device-info
[Debug]   Found build tasks:
[Debug]       TelegramNameChanger: build [.]
[Debug]   Resolving services with [raspberry-pi|rpi]
[Debug]   Found project types:
[Debug]       TelegramNameChanger: Standard Dockerfile
[Debug]   Probing remote daemon for cache images
[Debug]   Using 8 on-device images for cache...
[Debug]   Starting builds...
SecretRemovalError: The command '/bin/sh -c apk update && apk add bash jq' returned a non-zero code: 139
    at Object.<anonymous> (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:124:19)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:5:65)

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

Do I need to wait for another release or what? Is there any other viable solutions?

**Comment by pdcastro** [comment]
@JakeCover, the fix for `non-zero code: 139` was just [released](https://github.com/balena-io/balena-cli/releases) to balena-cli 11.14.1 and later. ([The PR you might have seen](https://github.com/balena-io/balena-cli/pull/1461) was still being tested and had not been merged). The new fix avoids the need for running `apk` at all (in that context), so at least those specific errors are guaranteed not to be seen anymore.

**Comment by JakeCover** [comment]
Ok thanks! I'll test it out tonight.

**Comment by pdcastro** [comment]
Closing this issue as it should be fixed with CLI v11.14.1 and later. It is still theoretically possible to have a `SecretRemovalError` under certain exceptional conditions, but it will no longer be related to `"apk update && apk add jq"` as these commands are no longer executed in the same context. If a `SecretRemovalError` was observed with CLI v11.14.1 or later, it would probably be the subject of a new Github issue.
