### ISSUE TITLE
preload: stuck at "Reading image information" spinner, errors not reported

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2045]
Originally reported by @chrisys ([internal flowdock thread](https://www.flowdock.com/app/rulemotion/r-product/threads/nSzIWfXQcDabItaQS5ZzSVNTfU9)):

> CLI preload looks like it's working but in the background has failed without informing the user, so you're left looking at a spinner thinking it's doing it's job (there are related issues for this but I think the worst aspect is that it doesn't even fail, it looks from the user pov as if everything is fine).

Steps to reproduce:

1. Using a recent version of Docker Desktop for macOS or Windows (which does not support the AUFS filesystem, e.g. Docker Desktop v2.3.0.5, Engine 19.03.12), attempt to preload an image that requires AUFS (raspberrypi3, intel-nuc). Do **not** enable debug mode (`export DEBUG=`).
2. Observe the CLI get stuck as follows:
```
$ balena preload balena-cloud-test-nuc-intel-nuc-2.50.1+rev1-v11.4.10.img -a test-nuc
Building Docker preloader image. [========================] 100%
| Checking that the image is a writable file
| Finding a free tcp port and getting balena settings
| Checking if the image is an edison zip archive
| Creating preloader container
\ Starting preloader container
/ Fetching application test-nuc
\ Reading image information
```

**Comment by vasdee** [comment]
I am facing this problem now. Are there any workarounds to get through? 

A team member didn't have this problem on a particular version of ubuntu, so my thinking is using a VM that has an older docker engine version might get me across the line

**Comment by chrisys** [comment]
@vasdee if you're on Linux it's my understanding that it should work OK, if you're on Windows/MacOS the options are to downgrade docker, or as you suggested, use a Ubuntu/Linux VM. I believe Docker Desktop 18.06.1 is the latest that supported the operation for Windows/Mac; see here for more: https://github.com/balena-io/balena-cli/issues/1099

**Comment by vasdee** [comment]
@chrisys interesting, this issue has occurred on both of my Linux installs - first was Arch Linux, second is a fresh install of Fedora 33.

As a test, I spun up a Ubuntu 20.04 VM in my Fedora install, it didn't have a problem running the same preload commands.  It looked like the docker versions between the Ubuntu VM and Fedora install were the same too, but I'll need to confirm that.

**Comment by pdcastro** [comment]
@vasdee, as you mention Arch Linux and Fedora 33, you may have come across another issue: #2250 which affects Linux distributions where cgroups v1 was disabled, and only cgroups v2 is available. If you run the `balena preload` command with the `--debug` flag, you may perhaps see the error `Error starting daemon: Devices cgroup isn't mounted`.

**Comment by vasdee** [comment]
@pdcastro yes, definitely saw that error and did notice the other ticket referencing the same.

I'm not across the low level implementation of docker and cgroups, is switching back to cgroups v1 possible via switches/config in the docker engine? 

Otherwise, I have a workaround for now that will allow me to create preloaded images so it's not a total showstopper.

**Comment by vasdee** [comment]
I've just tried this again with the latest v12.44.12 on Fedora 33. Looks like the problem is solved, at least for me!
 ```
$balena preload genericx86-64.img --app XXXXXX --commit 447faa1d --pin-device-to-release
Building Docker preloader image. [========================] 100%
| Checking that the image is a writable file
| Finding a free tcp port and getting balena settings
| Checking if the image is an edison zip archive
| Creating preloader container
\ Starting preloader container
- Fetching application XXXXXXXX/XXXXXXX
\ Reading image information
- Fetching application 1786259
\ Estimating required additional space
- Resizing partitions and waiting for dockerd to start
Pulling 10 images [========================] 100%
- Cleaning up temporary files
```

**Comment by pdcastro** [comment]
It has been reported that this issue still applies in CLI release 12.44.19, in connection to issue #1810.

**Comment by pdcastro** [comment]
CLI release 12.44.22 fixes additional cases where errors were "hidden" by the spinning wheels, including the case of issue #1810, even if --debug flag is not provided. Closing this issue because no known cases remain, but the issue can be reopened as needed.
(To be clear, closing this issue does not mean that the AUFS / graphdriver / sfdisk issues are "resolved", it only means that the errors are caught and reported straight away, instead of hidden under infinite spinning wheels.)
