### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by xoul** [balena-io/balena-cli#653]
I've just update resin-cli to 6.6.5 on a system running CentOS 7.3 and Node 6.11.1:

```
[root@asgard resin]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@asgard resin]# rpm -qa | grep nodejs
nodejs-6.11.1-1.el7.x86_64
```

Now when I try to login using "credentials" I run into this error:

```
$ resin login --credentials --email myemail --password mypassword
______          _         _
| ___ \        (_)       (_)
| |_/ /___  ___ _ _ __    _  ___
|    // _ \/ __| | '_ \  | |/ _ \
| |\ \  __/\__ \ | | | |_| | (_) |
\_| \_\___||___/_|_| |_(_)_|\___/

Logging in to resin.io
Cannot read property 'isValid' of undefined

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

```

I've also tried to login using "web", but the command do not returs:

```
$ resin login --web --email myemail --password mypassword
______          _         _
| ___ \        (_)       (_)
| |_/ /___  ___ _ _ __    _  ___
|    // _ \/ __| | '_ \  | |/ _ \
| |\ \  __/\__ \ | | | |_| | (_) |
\_| \_\___||___/_|_| |_(_)_|\___/

Logging in to resin.io
Connecting to the web dashboard


```

**Comment by xoul** [comment]
Even tried to reinstall NodeJS and the install resin-cli from scratch, but with the same errors as shown above:

```
[root@asgard resin]# npm install --global resin-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/bin/resin -> /usr/lib/node_modules/resin-cli/bin/resin
/usr/lib
└─┬ resin-cli@6.6.5
  ├── global-tunnel-ng@2.1.0  (git://github.com/zvin/global-tunnel.git#fa05adbe0af2b6355e29b32271ffdf8b00e1ceb5)
  └─┬ resin-sync@9.1.0
    └─┬ resin-discoverable-services@1.2.2  (git+https://github.com/resin-io-modules/resin-discoverable-services.git#afca9e4700ec5ef82aa897f14bd5a46f06518061)
      └─┬ bonjour@3.5.0  (git+https://github.com/resin-io/bonjour.git#e018851dc823b4b3f670f658f71d0c1c7f3e637c)
        └── multicast-dns@6.1.1  (git+https://github.com/resin-io-modules/multicast-dns.git#a15c63464eb43e8925b187ed5cb9de6892e8aacc)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@^1.0.0 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macmount@^1.0.0 (node_modules/resin-cli/node_modules/denymount/node_modules/macmount):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macmount@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```

**Comment by pimterry** [comment]
Hi @xoul, sorry about this, it was due to a bug that got released in `resin-token` (one of the submodules used in the CLI). It's since [been fixed](https://github.com/resin-io-modules/resin-token/pull/33), and was released in resin-token 4.2.1 on Tuesday last week. If you uninstall and reinstall `resin-cli`, everything should work nicely now.

I'm going to close this as resolved, but feel free to reopen if you're still having any trouble.

**Comment by devxpy** [comment]
Still having this issue on resin-token 4.2.1

**Comment by devxpy** [comment]
- resin-cli@7.6.2
- I tried both npm and standalone
- node v8.11.3 (npm 5.6.0)
- Solus 3.999 (linux 4.17.2-78.current)
- Same as the @xoul, its just stuck.

```
⋊ ~> resin login --web
______          _         _
| ___ \        (_)       (_)
| |_/ /___  ___ _ _ __    _  ___
|    // _ \/ __| | '_ \  | |/ _ \
| |\ \  __/\__ \ | | | |_| | (_) |
\_| \_\___||___/_|_| |_(_)_|\___/

Logging in to resin.io
Connecting to the web dashboard
 ```

web browser - Google chrome

**Comment by pimterry** [comment]
@devxpy if you try using `--credentials` instead, as in the first post above, does that work for you?

We should fix the web login regardless ofc. That works by opening a resin dashboard URL in your browser using [opn](https://npmjs.com/package/opn). It sounds like you're not seeing a browser appear at all, which is definitely unusual. Can you run `node` in your installed CLI folder, and run the below?

```js
const opn = require('opn');
opn('http://example.com');
```

It everything is working well, that should open your browser, using xdg-open. Can you confirm whether that works? If not, can you try `./node_modules/opn/xdg-open http://example.com` as well?

**Comment by devxpy** [comment]
```
Welcome to fish, the friendly interactive shell
⋊ ~> node
> const opn = require('opn');
Error: Cannot find module 'opn'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
> opn('http://example.com');
ReferenceError: opn is not defined
> 
```
So, i ran `npm -g i opn`
```
⋊ ~> npm -g i opn
+ opn@5.3.0
added 2 packages from 1 contributor in 2.665s
```

And I still get that error.

`node_modules/opn/xdg-open http://example.com` runs fine though.


On a different note, does resin itself rely on nodejs? This kind of stuff is quite easy and actually, in-built in a battries included languages like python.

**Comment by pimterry** [comment]
Hmm, ok @devxpy are you definitely in resin-cli's installed folder there? For global installs on Linux it's probably somewhere like `/usr/local/lib/node_modules/resin-cli`. There should be a `node_modules/opn` folder within that. I'd be very surprised if opn is missing somehow, that would result in some much clearer & louder errors from the CLI itself.

Have you tried the `--credentials` workaround?

Also, what's your Resin username? We've got some error logging indexed by user, so that might let me get a little more info, if there are any more errors being reported.

Sorry I can't be more helpful here, I can't reproduce this myself at all, which makes it very difficult to debug! You can see the logic that opens the web browser for yourself [here](https://github.com/resin-io/resin-cli/blob/master/lib/auth/index.coffee#L58-L60) and given that the browser isn't opening at all though, it's definitely sounds like it's that that's failing, it's just not clear why.

> On a different note, does resin itself rely on nodejs?

Most of the Resin infrastructure is built on node, but as a user in general you don't need to use node at all.

**Comment by devxpy** [comment]
I tried again using latest standalone, and re-installed node. Seems to work now.

**Comment by devxpy** [comment]
standalone build. Re-installed node, same version.

**Comment by devxpy** [comment]
It broke again...

Looks like it's a bug with the fish shell. It works fine on bash.

**Comment by pimterry** [comment]
Hmm, ok... I've just installed fish myself locally, and it works fine there for me. Is it possibly something to do with the specific configuration of your shell?

**Comment by devxpy** [comment]
Probably, It started working again when I reinstalled it...
